/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jackfahdin_SerialPortJNI_SerialPort */

#ifndef Included_com_jackfahdin_SerialPortJNI_SerialPort
#define Included_com_jackfahdin_SerialPortJNI_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jackfahdin_SerialPortJNI_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;IIIII)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_jackfahdin_SerialPortJNI_SerialPort_open
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     com_jackfahdin_SerialPortJNI_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jackfahdin_SerialPortJNI_SerialPort_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
